DreamShop/DreamShop.Web/Controllers/AuthController.cs
using System.IdentityModel.Tokens.Jwt;
using DreamShop.Web.Models.DTOs;
using DreamShop.Web.Service.IService;
using DreamShop.Web.Utilities;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace DreamShop.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;
        private readonly ITokenProvider _tokenProvider;

        public AuthController(IAuthService authService, ITokenProvider tokenProvider)
        {
            _authService = authService;
            _tokenProvider = tokenProvider;
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserLoginRequestDto userLoginRequestDto)
        {
            var isLoggedIn = await _authService.UserLogin(userLoginRequestDto);
            if (isLoggedIn.IsSuccess)
            {
                var loginResponse = Utility.MapToResponse<UserLoginResponseDto>(isLoggedIn.Result);
                await SignInUser(loginResponse);
                _tokenProvider.SetToken(loginResponse.Token);
                TempData["success"] = "User logged in successfully.";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("CustomError", isLoggedIn.Message);
                return View(userLoginRequestDto);
            }
        }

        [HttpGet]
        public IActionResult Register()
        {
            var roleList = GetRoles();
            ViewBag.RoleList = roleList;
            return View(new UserRegistrationRequestDto());
        }
        
        [HttpPost]
        public async Task<IActionResult> Register(UserRegistrationRequestDto userRegistrationRequest)
        {
            var userRegisterResult = await _authService.UserRegistration(userRegistrationRequest);
            if (userRegisterResult.IsSuccess)
            {
                if (string.IsNullOrEmpty(userRegistrationRequest.Role))
                {
                    userRegistrationRequest.Role = Utility.CustomerRole;
                }

                var roleAssignResult = await _authService.AssignUserRole(userRegistrationRequest);
                if (roleAssignResult.IsSuccess)
                {
                    TempData["success"] = "User registration successful.";
                    return RedirectToAction(nameof(Login));
                }
            }


            var roleList = GetRoles();
            ViewBag.RoleList = roleList;
            return View(userRegistrationRequest);
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            _tokenProvider.ClearToken();
            TempData["info"] = "Logout successfully.";
            return RedirectToAction("Index", "Home");
        }

        private static List<SelectListItem> GetRoles()
        {
            var roleList = new List<SelectListItem>()
            {
                new SelectListItem(text: Utility.AdminRole, value: Utility.AdminRole),
                new SelectListItem(text: Utility.CustomerRole, value: Utility.CustomerRole),
            };
            return roleList;
        }

        private async Task SignInUser(UserLoginResponseDto model)
        {
            var handler = new JwtSecurityTokenHandler();

            var jwt = handler.ReadJwtToken(model.Token);

            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Sub).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Name).Value));


            identity.AddClaim(new Claim(ClaimTypes.Name,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
            identity.AddClaim(new Claim(ClaimTypes.Role,
                jwt.Claims.FirstOrDefault(u => u.Type == "role").Value));



            var principal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
        }
    }
}

DreamShop/DreamShop.Web/Controllers/CartController.cs
using DreamShop.Web.Models.DTOs;
using DreamShop.Web.Service.IService;
using DreamShop.Web.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.JsonWebTokens;

namespace DreamShop.Web.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        private readonly IOrderService _orderService;

        public CartController(ICartService cartService, IOrderService orderService)
        {
            _cartService = cartService;
            _orderService = orderService;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await GetCartForLoggedInUser());
        }

        [Authorize]
        public async Task<IActionResult> Checkout()
        {
            return View(await GetCartForLoggedInUser());
        }

        [HttpPost]
        [ActionName("Checkout")]
        public async Task<IActionResult> Checkout(CartHeaderDto cartHeaderDto)
        {
            var cart = await GetCartForLoggedInUser();
            cart.FirstName = cartHeaderDto.FirstName;
            cart.LastName = cartHeaderDto.LastName;
            cart.Email = cartHeaderDto.Email;
            cart.Phone = cartHeaderDto.Phone;

            var response = await _orderService.CreateOrderAsync(cart);
            if (response != null && response.IsSuccess)
            {
                var order = Utility.MapToResponse<OrderHeaderDto>(response.Result);
                TempData["success"] = "Order has been created.";
                return RedirectToAction(nameof(Confirmation), new{OrderId = order.Id});
            }
            else
            {
                TempData["error"] = "Order could not be created! Please try again later.";
            }

            return View(cartHeaderDto);
        }

        public async Task<IActionResult> Confirmation(long orderId)
        {
            return View(orderId);
        }

        [HttpPost]
        public async Task<IActionResult> ApplyCoupon(CartHeaderDto cart)
        {
            var response = await _cartService.AddCoupon(cart);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Coupon added successfully.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["error"] = "Coupon added failed!";
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> EmailCart(CartHeaderDto cart)
        {
            var cartData = await GetCartForLoggedInUser();
            cartData.Email = User.Claims.Where(c => c.Type == JwtRegisteredClaimNames.Email)?.FirstOrDefault()?.Value;
            
            // email logging using azure service bus
            var response = await _cartService.CartEmailRequest(cartData);

            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Email will be processed and send shortly.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["error"] = "Email sent failed!";
            }

            return View(cart);
        }


        public async Task<IActionResult> Remove(long detailsId)
        {
            var response = await _cartService.RemoveCart(detailsId);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Item deleted from cart successfully.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["error"] = "Items cart delete operation failed!";
            }

            return View();
        }

        public async Task<CartHeaderDto> GetCartForLoggedInUser()
        {
            var userId = User.Claims.Where(c => c.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;
            var response = await _cartService.GetCartsByUserIdAsync(userId);
            if (response != null)
            {
                var data = Utility.MapToResponse<CartHeaderDto>(response.Result);
                return data;
            }

            return new();
        }
    }
}

DreamShop/DreamShop.Web/Controllers/CouponController.cs
using DreamShop.Web.Models.DTOs;
using DreamShop.Web.Service.IService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using Newtonsoft.Json;

namespace DreamShop.Web.Controllers
{
    
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;

        public CouponController(ICouponService couponService)
        {
            _couponService = couponService;
        }
        public async Task<IActionResult> Index()
        {
            List<CouponDto> coupons = new List<CouponDto>();
            var data = await _couponService.GetAllCoupons();

            if (data != null && data.IsSuccess)
            {
                coupons = JsonConvert.DeserializeObject<List<CouponDto>>(Convert.ToString(data.Result));
            }
            else
            {
                TempData["error"] = data.Message;
            }

            return View(coupons);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CouponDto coupon)
        {
            if (ModelState.IsValid)
            {
                var response = await _couponService.CreateCoupon(coupon);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(coupon);
        }
        
        public async Task<IActionResult> Delete(long couponId)
        {
            var existingCoupon = await _couponService.GetCouponById(couponId);
            if (existingCoupon != null && existingCoupon.IsSuccess)
            {
                var couponToDelete = JsonConvert.DeserializeObject<CouponDto>(Convert.ToString(existingCoupon.Result));
                return View(couponToDelete);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(CouponDto coupon)
        {
            var existingCoupon = await _couponService.DeleteCoupon(coupon.Id);
            if (existingCoupon != null && existingCoupon.IsSuccess)
            {
                TempData["success"] = "Coupon deleted successfully.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["error"] = "Coupon delete operation failed!";
                return NotFound();
            }
        }
    }
}

DreamShop/DreamShop.Web/Controllers/OrderController.cs
using DreamShop.Web.Models.DTOs;
using DreamShop.Web.Service.IService;
using DreamShop.Web.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.JsonWebTokens;
using Newtonsoft.Json;

namespace DreamShop.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public IActionResult GetAll(string status)
        {
            IEnumerable<OrderHeaderDto> list;
            string userId = "";
            if (!User.IsInRole(Utility.AdminRole))
            {
                userId = User.Claims.Where(u => u.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;
            }
            ResponseDto response = _orderService.GetAllOrdersAsync(userId).GetAwaiter().GetResult();
            if (response != null && response.IsSuccess)
            {
                list = Utility.MapToResponse<IEnumerable<OrderHeaderDto>>(response.Result);
                switch (status)
                {
                    case "approved":
                        list = list.Where(u => u.Status == Utility.Status_Approved);
                        break;
                    case "readyforpickup":
                        list = list.Where(u => u.Status == Utility.Status_ReadyForPickup);
                        break;
                    case "cancelled":
                        list = list.Where(u => u.Status == Utility.Status_Cancelled || u.Status == Utility.Status_Refund);
                        break;
                    default:
                        break;
                }
            }
            else
            {
                list = new List<OrderHeaderDto>();
            }
            return Json(new { data = list.OrderByDescending(u => u.Id) });
        }


        [Authorize]
        public async Task<IActionResult> OrderDetail(int orderId)
        {
            OrderHeaderDto orderHeaderDto = new OrderHeaderDto();
            string userId = User.Claims.Where(u => u.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;

            var response = await _orderService.GetOrderByIdAsync(orderId);
            if (response != null && response.IsSuccess)
            {
                orderHeaderDto = JsonConvert.DeserializeObject<OrderHeaderDto>(Convert.ToString(response.Result));
            }
            if (!User.IsInRole(Utility.AdminRole) && userId != orderHeaderDto.UserId)
            {
                return NotFound();
            }
            return View(orderHeaderDto);
        }

        [HttpPost("OrderReadyForPickup")]
        public async Task<IActionResult> OrderReadyForPickup(int orderId)
        {
            var response = await _orderService.UpdateOrderStatusAsync(orderId, Utility.Status_ReadyForPickup);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Status updated successfully";
                return RedirectToAction(nameof(OrderDetail), new { orderId = orderId });
            }
            return View();
        }

        [HttpPost("CompleteOrder")]
        public async Task<IActionResult> CompleteOrder(int orderId)
        {
            var response = await _orderService.UpdateOrderStatusAsync(orderId, Utility.Status_Completed);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Status updated successfully";
                return RedirectToAction(nameof(OrderDetail), new { orderId = orderId });
            }
            return View();
        }

        [HttpPost("CancelOrder")]
        public async Task<IActionResult> CancelOrder(int orderId)
        {
            var response = await _orderService.UpdateOrderStatusAsync(orderId, Utility.Status_Cancelled);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Status updated successfully";
                return RedirectToAction(nameof(OrderDetail), new { orderId = orderId });
            }
            return View();
        }

    }
}

DreamShop/DreamShop.Web/Views/Shared/_Layout.cshtml
@using DreamShop.Web.Utilities
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DreamShop.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.7/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DreamShop.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DreamShop.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(Utility.AdminRole))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-controller="Coupon" asp-action="Index">Coupon</a></li>
                                    <li><a class="dropdown-item" asp-controller="Product" asp-action="Index">Product</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Order" asp-action="Index">
                                Manage Orders
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Cart" asp-action="Index">
                                <i class="bi bi-cart"></i>
                            </a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link">Hi, @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notification" />
        </main>
    </div>

    <footer class=" footer text-muted">
        <div class="text-center">
            &copy; 2024 - Dream <i class="bi bi-balloon-heart-fill"></i> Shop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.datatables.net/2.0.7/js/dataTables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DreamShop/DreamShop.Web/Views/Shared/_Notification.cshtml
@if(TempData["error"]!=null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
        </script>
}

@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

@if (TempData["info"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.info('@TempData["info"]')
    </script>
}

@if (TempData["warning"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.warning('@TempData["warning"]')
    </script>
}